# Generated by Django 3.1.1 on 2020-09-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='null', max_length=225),
            preserve_default=False,
        ),
    ]
