# Generated by Django 3.1.1 on 2020-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='court',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='experience',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='fees',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='speciality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
