# Generated by Django 3.1.1 on 2020-11-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201117_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
