# Generated by Django 3.1.1 on 2020-11-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201118_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
