# Generated by Django 3.1.1 on 2020-10-23 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201023_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=300, unique_for_date='created'),
            preserve_default=False,
        ),
    ]
