# Generated by Django 3.1.1 on 2020-11-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201024_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_reply',
            options={'ordering': ('date_added',)},
        ),
    ]
